import React, { useState } from 'react';
import IssuesList from './IssuesList';
const example = [
  {
    id: 1,
    description:
      'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.',
    reported_count: null,
    user_id: 998643,
    img: 'http://dummyimage.com/168x236.png/ff4444/ffffff',
    upvoted_count: 84,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 9,
    task_owner: 'agirsch0',
    borough: 'Bijeli',
    title: 'interdum eu tincidunt in leo maecenas',
  },
  {
    id: 2,
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.',
    reported_count: 16,
    user_id: 955209,
    img: 'http://dummyimage.com/148x214.bmp/ff4444/ffffff',
    upvoted_count: 31,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'kveazey1',
    borough: 'Shchūchīnsk',
    title: 'semper porta volutpat quam pede lobortis ligula',
  },
  {
    id: 3,
    description: 'Sed accumsan felis.',
    reported_count: null,
    user_id: 156694,
    img: 'http://dummyimage.com/199x165.bmp/ff4444/ffffff',
    upvoted_count: 3,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 8,
    task_owner: 'mforryan2',
    borough: 'Oakland',
    title: 'eros viverra eget congue',
  },
  {
    id: 4,
    description:
      'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    reported_count: 2,
    user_id: 393853,
    img: 'http://dummyimage.com/236x131.bmp/cc0000/ffffff',
    upvoted_count: 16,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Gwio Kura',
    title: 'orci pede venenatis non sodales sed',
  },
  {
    id: 5,
    description:
      'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    reported_count: 10,
    user_id: 273130,
    img: 'http://dummyimage.com/209x188.bmp/5fa2dd/ffffff',
    upvoted_count: 60,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ovassall4',
    borough: 'Färgelanda',
    title: 'nulla ut erat id',
  },
  {
    id: 6,
    description:
      'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    reported_count: null,
    user_id: 651580,
    img: 'http://dummyimage.com/237x217.bmp/cc0000/ffffff',
    upvoted_count: 90,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 9,
    task_owner: 'rdavidovics5',
    borough: 'Maomiaoji',
    title: 'nulla sed vel enim sit amet nunc',
  },
  {
    id: 7,
    description:
      'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    reported_count: 8,
    user_id: 899653,
    img: 'http://dummyimage.com/234x247.jpg/dddddd/000000',
    upvoted_count: 12,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 10,
    task_owner: 'ysimionato6',
    borough: 'Courtaboeuf',
    title: 'lobortis ligula sit amet',
  },
  {
    id: 8,
    description: 'Aenean lectus.',
    reported_count: 3,
    user_id: 735802,
    img: 'http://dummyimage.com/208x130.bmp/cc0000/ffffff',
    upvoted_count: 73,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 4,
    task_owner: 'stremblot7',
    borough: 'Kaliro',
    title: 'vestibulum sagittis sapien cum sociis',
  },
  {
    id: 9,
    description:
      'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
    reported_count: null,
    user_id: 582761,
    img: 'http://dummyimage.com/184x189.jpg/ff4444/ffffff',
    upvoted_count: 95,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'spaszak8',
    borough: 'Karlstad',
    title: 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur',
  },
  {
    id: 10,
    description:
      'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',
    reported_count: 9,
    user_id: 163408,
    img: 'http://dummyimage.com/219x120.png/ff4444/ffffff',
    upvoted_count: 52,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 0,
    task_owner: 'clamden9',
    borough: 'Vichadero',
    title: 'cubilia curae mauris viverra diam vitae quam suspendisse',
  },
  {
    id: 11,
    description:
      'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    reported_count: null,
    user_id: 204249,
    img: 'http://dummyimage.com/165x248.jpg/dddddd/000000',
    upvoted_count: 79,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'csibbita',
    borough: 'Ungheni',
    title: 'condimentum id luctus nec molestie',
  },
  {
    id: 12,
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
    reported_count: null,
    user_id: 372618,
    img: 'http://dummyimage.com/147x155.jpg/5fa2dd/ffffff',
    upvoted_count: 56,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'mwalkingtonb',
    borough: 'Isehara',
    title: 'nascetur ridiculus mus vivamus vestibulum sagittis sapien',
  },
  {
    id: 13,
    description:
      'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
    reported_count: null,
    user_id: 317005,
    img: 'http://dummyimage.com/155x128.png/5fa2dd/ffffff',
    upvoted_count: 86,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Krasnaya Polyana',
    title: 'varius nulla facilisi cras non velit nec nisi vulputate',
  },
  {
    id: 14,
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.',
    reported_count: 12,
    user_id: 757233,
    img: 'http://dummyimage.com/201x242.jpg/dddddd/000000',
    upvoted_count: 30,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'gmackinderd',
    borough: 'Tangba',
    title: 'sed tristique in tempus sit amet sem fusce consequat nulla',
  },
  {
    id: 15,
    description:
      'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    reported_count: 11,
    user_id: 218289,
    img: 'http://dummyimage.com/156x143.jpg/5fa2dd/ffffff',
    upvoted_count: 36,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Tengah',
    title: 'leo odio condimentum id luctus nec molestie',
  },
  {
    id: 16,
    description:
      'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    reported_count: 16,
    user_id: 471564,
    img: 'http://dummyimage.com/164x225.jpg/ff4444/ffffff',
    upvoted_count: 80,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Dolinsk',
    title: 'in sagittis dui vel',
  },
  {
    id: 17,
    description:
      'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    reported_count: null,
    user_id: 839671,
    img: 'http://dummyimage.com/156x171.png/ff4444/ffffff',
    upvoted_count: 59,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Pátmos',
    title: 'quis augue luctus tincidunt nulla',
  },
  {
    id: 18,
    description:
      'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    reported_count: 20,
    user_id: 665070,
    img: 'http://dummyimage.com/106x244.jpg/cc0000/ffffff',
    upvoted_count: 50,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Norrköping',
    title: 'morbi quis tortor id',
  },
  {
    id: 19,
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.',
    reported_count: null,
    user_id: 192858,
    img: 'http://dummyimage.com/115x169.bmp/ff4444/ffffff',
    upvoted_count: 41,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Lyon',
    title: 'vel dapibus at diam nam tristique tortor eu',
  },
  {
    id: 20,
    description: 'Curabitur in libero ut massa volutpat convallis.',
    reported_count: 18,
    user_id: 310811,
    img: 'http://dummyimage.com/189x225.bmp/ff4444/ffffff',
    upvoted_count: 18,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 8,
    task_owner: 'dbrimelowj',
    borough: 'Nogueira',
    title: 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo',
  },
  {
    id: 21,
    description:
      'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
    reported_count: null,
    user_id: 586896,
    img: 'http://dummyimage.com/179x136.bmp/ff4444/ffffff',
    upvoted_count: 50,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'cmacredmondk',
    borough: 'Bobigny',
    title: 'eu nibh quisque id justo',
  },
  {
    id: 22,
    description:
      'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.',
    reported_count: 3,
    user_id: 958694,
    img: 'http://dummyimage.com/184x167.bmp/ff4444/ffffff',
    upvoted_count: 92,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Massy',
    title: 'sem sed sagittis nam',
  },
  {
    id: 23,
    description: 'Morbi quis tortor id nulla ultrices aliquet.',
    reported_count: 17,
    user_id: 138154,
    img: 'http://dummyimage.com/181x125.png/cc0000/ffffff',
    upvoted_count: 10,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 5,
    task_owner: 'tslym',
    borough: 'Ruše',
    title: 'nullam molestie nibh in lectus pellentesque',
  },
  {
    id: 24,
    description:
      'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',
    reported_count: 14,
    user_id: 662637,
    img: 'http://dummyimage.com/117x100.jpg/ff4444/ffffff',
    upvoted_count: 50,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 6,
    task_owner: 'eguesten',
    borough: 'Uppsala',
    title: 'morbi sem mauris laoreet',
  },
  {
    id: 25,
    description: 'Nam tristique tortor eu pede.',
    reported_count: null,
    user_id: 949236,
    img: 'http://dummyimage.com/246x233.bmp/dddddd/000000',
    upvoted_count: 51,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 1,
    task_owner: 'swhitchero',
    borough: 'Akureyri',
    title: 'pretium nisl ut volutpat sapien arcu sed augue',
  },
  {
    id: 26,
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',
    reported_count: null,
    user_id: 754041,
    img: 'http://dummyimage.com/168x225.png/ff4444/ffffff',
    upvoted_count: 100,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'bcleariep',
    borough: 'Waru',
    title: 'proin leo odio porttitor id',
  },
  {
    id: 27,
    description:
      'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.',
    reported_count: null,
    user_id: 811225,
    img: 'http://dummyimage.com/131x174.png/5fa2dd/ffffff',
    upvoted_count: 44,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 8,
    task_owner: 'rmenchentonq',
    borough: 'Jasionów',
    title: 'penatibus et magnis dis parturient montes nascetur ridiculus mus',
  },
  {
    id: 28,
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    reported_count: null,
    user_id: 471255,
    img: 'http://dummyimage.com/125x145.png/dddddd/000000',
    upvoted_count: 81,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Xudat',
    title: 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam',
  },
  {
    id: 29,
    description:
      'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
    reported_count: 17,
    user_id: 318247,
    img: 'http://dummyimage.com/177x176.bmp/cc0000/ffffff',
    upvoted_count: 26,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Ankazondandy',
    title: 'nulla neque libero convallis eget eleifend',
  },
  {
    id: 30,
    description:
      'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    reported_count: null,
    user_id: 989591,
    img: 'http://dummyimage.com/151x100.png/cc0000/ffffff',
    upvoted_count: 11,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'wolrenshawt',
    borough: 'Bagay',
    title: 'sem fusce consequat nulla nisl',
  },
  {
    id: 31,
    description:
      'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
    reported_count: null,
    user_id: 279438,
    img: 'http://dummyimage.com/156x245.bmp/dddddd/000000',
    upvoted_count: 8,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 1,
    task_owner: 'mvasiljevicu',
    borough: 'Milicz',
    title: 'leo pellentesque ultrices mattis odio donec vitae',
  },
  {
    id: 32,
    description: 'Suspendisse potenti.',
    reported_count: null,
    user_id: 689686,
    img: 'http://dummyimage.com/187x249.png/dddddd/000000',
    upvoted_count: 37,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'raskellv',
    borough: 'Kertamukti',
    title: 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor',
  },
  {
    id: 33,
    description:
      'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
    reported_count: 16,
    user_id: 256710,
    img: 'http://dummyimage.com/151x140.jpg/ff4444/ffffff',
    upvoted_count: 22,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 10,
    task_owner: 'egannw',
    borough: 'Sironko',
    title: 'consequat nulla nisl nunc nisl duis bibendum felis sed',
  },
  {
    id: 34,
    description: 'Nullam sit amet turpis elementum ligula vehicula consequat.',
    reported_count: 6,
    user_id: 531336,
    img: 'http://dummyimage.com/198x168.jpg/dddddd/000000',
    upvoted_count: 28,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'dadrianox',
    borough: 'Gémeos',
    title: 'nulla facilisi cras non velit nec nisi',
  },
  {
    id: 35,
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    reported_count: 1,
    user_id: 600569,
    img: 'http://dummyimage.com/117x203.png/cc0000/ffffff',
    upvoted_count: 100,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 7,
    task_owner: 'tbeamsy',
    borough: 'Hartford',
    title: 'venenatis non sodales sed tincidunt eu felis fusce',
  },
  {
    id: 36,
    description:
      'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    reported_count: 5,
    user_id: 928244,
    img: 'http://dummyimage.com/181x240.jpg/dddddd/000000',
    upvoted_count: 13,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Jorf',
    title: 'nunc vestibulum ante ipsum primis',
  },
  {
    id: 37,
    description: 'Morbi non quam nec dui luctus rutrum.',
    reported_count: 2,
    user_id: 896297,
    img: 'http://dummyimage.com/149x230.jpg/ff4444/ffffff',
    upvoted_count: 46,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 0,
    task_owner: 'dbramley10',
    borough: 'Saint Paul',
    title: 'proin leo odio porttitor id',
  },
  {
    id: 38,
    description:
      'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    reported_count: 16,
    user_id: 273809,
    img: 'http://dummyimage.com/235x142.bmp/5fa2dd/ffffff',
    upvoted_count: 61,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Puerto Barrios',
    title: 'nibh ligula nec sem duis aliquam convallis nunc',
  },
  {
    id: 39,
    description:
      'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
    reported_count: null,
    user_id: 645009,
    img: 'http://dummyimage.com/132x239.bmp/ff4444/ffffff',
    upvoted_count: 19,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Smederevska Palanka',
    title: 'erat nulla tempus vivamus in felis eu',
  },
  {
    id: 40,
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',
    reported_count: null,
    user_id: 149512,
    img: 'http://dummyimage.com/175x161.png/ff4444/ffffff',
    upvoted_count: 31,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ldemeter13',
    borough: 'Skanör',
    title: 'vitae mattis nibh ligula nec sem duis aliquam',
  },
  {
    id: 41,
    description: 'In congue.',
    reported_count: 4,
    user_id: 850417,
    img: 'http://dummyimage.com/108x137.jpg/ff4444/ffffff',
    upvoted_count: 68,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 1,
    task_owner: 'fbraywood14',
    borough: 'Yŏnggwang-ŭp',
    title: 'etiam faucibus cursus urna ut tellus',
  },
  {
    id: 42,
    description:
      'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',
    reported_count: null,
    user_id: 428071,
    img: 'http://dummyimage.com/155x198.bmp/ff4444/ffffff',
    upvoted_count: 95,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 8,
    task_owner: 'vmccullough15',
    borough: 'Buensuseso',
    title: 'amet erat nulla tempus vivamus in felis eu',
  },
  {
    id: 43,
    description:
      'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',
    reported_count: null,
    user_id: 422755,
    img: 'http://dummyimage.com/173x183.png/5fa2dd/ffffff',
    upvoted_count: 81,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 2,
    task_owner: 'arentcome16',
    borough: 'Shazhouba',
    title: 'diam erat fermentum justo nec condimentum neque',
  },
  {
    id: 44,
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',
    reported_count: 18,
    user_id: 476095,
    img: 'http://dummyimage.com/200x207.jpg/5fa2dd/ffffff',
    upvoted_count: 18,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 2,
    task_owner: 'kdabels17',
    borough: 'Fuwah',
    title: 'ligula vehicula consequat morbi a ipsum',
  },
  {
    id: 45,
    description: 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.',
    reported_count: 9,
    user_id: 427642,
    img: 'http://dummyimage.com/242x147.bmp/5fa2dd/ffffff',
    upvoted_count: 100,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'mhargitt18',
    borough: 'Az Zāhir',
    title: 'leo maecenas pulvinar lobortis est phasellus sit amet',
  },
  {
    id: 46,
    description:
      'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    reported_count: null,
    user_id: 211702,
    img: 'http://dummyimage.com/113x164.bmp/dddddd/000000',
    upvoted_count: 49,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'hport19',
    borough: 'Kolsko',
    title: 'natoque penatibus et magnis dis parturient',
  },
  {
    id: 47,
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    reported_count: 15,
    user_id: 545187,
    img: 'http://dummyimage.com/113x171.bmp/ff4444/ffffff',
    upvoted_count: 61,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 6,
    task_owner: 'wteal1a',
    borough: 'Hovězí',
    title: 'fusce consequat nulla nisl nunc nisl duis',
  },
  {
    id: 48,
    description:
      'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    reported_count: null,
    user_id: 582575,
    img: 'http://dummyimage.com/110x168.bmp/dddddd/000000',
    upvoted_count: 69,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'cholstein1b',
    borough: 'Baiima',
    title: 'nisl duis ac nibh fusce lacus purus aliquet at',
  },
  {
    id: 49,
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    reported_count: null,
    user_id: 420053,
    img: 'http://dummyimage.com/154x145.bmp/cc0000/ffffff',
    upvoted_count: 68,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'bdufore1c',
    borough: 'Padre Paraíso',
    title: 'nunc nisl duis bibendum felis sed interdum',
  },
  {
    id: 50,
    description: 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    reported_count: null,
    user_id: 918774,
    img: 'http://dummyimage.com/183x131.png/5fa2dd/ffffff',
    upvoted_count: 56,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'acocozza1d',
    borough: 'Khondāb',
    title: 'neque aenean auctor gravida',
  },
  {
    id: 51,
    description:
      'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',
    reported_count: null,
    user_id: 947523,
    img: 'http://dummyimage.com/192x106.bmp/cc0000/ffffff',
    upvoted_count: 90,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 6,
    task_owner: 'lthexton1e',
    borough: 'Niquelândia',
    title: 'dapibus augue vel accumsan tellus nisi eu orci',
  },
  {
    id: 52,
    description:
      'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    reported_count: 8,
    user_id: 942227,
    img: 'http://dummyimage.com/187x195.png/cc0000/ffffff',
    upvoted_count: 24,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Shimonoseki',
    title: 'molestie sed justo pellentesque viverra pede ac',
  },
  {
    id: 53,
    description: 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    reported_count: null,
    user_id: 523007,
    img: 'http://dummyimage.com/205x171.png/ff4444/ffffff',
    upvoted_count: 100,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'imckellen1g',
    borough: 'Oromocto',
    title: 'odio odio elementum eu interdum eu',
  },
  {
    id: 54,
    description:
      'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    reported_count: null,
    user_id: 572846,
    img: 'http://dummyimage.com/132x170.jpg/ff4444/ffffff',
    upvoted_count: 20,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 2,
    task_owner: 'babraham1h',
    borough: 'Pniewy',
    title: 'blandit lacinia erat vestibulum sed magna',
  },
  {
    id: 55,
    description:
      'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
    reported_count: null,
    user_id: 178040,
    img: 'http://dummyimage.com/107x248.bmp/dddddd/000000',
    upvoted_count: 53,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 3,
    task_owner: 'bstanner1i',
    borough: 'Concordia',
    title: 'iaculis congue vivamus metus arcu adipiscing molestie',
  },
  {
    id: 56,
    description:
      'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',
    reported_count: null,
    user_id: 449806,
    img: 'http://dummyimage.com/171x194.jpg/dddddd/000000',
    upvoted_count: 73,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'New Mīrpur',
    title: 'sagittis dui vel nisl duis ac nibh fusce',
  },
  {
    id: 57,
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    reported_count: 14,
    user_id: 767421,
    img: 'http://dummyimage.com/186x247.bmp/ff4444/ffffff',
    upvoted_count: 27,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'mfeilden1k',
    borough: 'Municipio de Copacabana',
    title: 'sit amet sapien dignissim',
  },
  {
    id: 58,
    description: 'Nulla ut erat id mauris vulputate elementum.',
    reported_count: 14,
    user_id: 296562,
    img: 'http://dummyimage.com/243x135.bmp/5fa2dd/ffffff',
    upvoted_count: 53,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Hrotovice',
    title: 'a pede posuere nonummy integer non',
  },
  {
    id: 59,
    description:
      'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    reported_count: 18,
    user_id: 975708,
    img: 'http://dummyimage.com/236x182.jpg/dddddd/000000',
    upvoted_count: 4,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Senekal',
    title: 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer',
  },
  {
    id: 60,
    description:
      'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    reported_count: 4,
    user_id: 508307,
    img: 'http://dummyimage.com/174x211.jpg/dddddd/000000',
    upvoted_count: 14,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 9,
    task_owner: 'ngenty1n',
    borough: 'Hucheng',
    title: 'parturient montes nascetur ridiculus mus vivamus vestibulum',
  },
  {
    id: 61,
    description:
      'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
    reported_count: 17,
    user_id: 167291,
    img: 'http://dummyimage.com/241x124.bmp/5fa2dd/ffffff',
    upvoted_count: 77,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'bmordanti1o',
    borough: 'Xikou',
    title: 'turpis a pede posuere nonummy integer non velit donec',
  },
  {
    id: 62,
    description:
      'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.',
    reported_count: 13,
    user_id: 687768,
    img: 'http://dummyimage.com/103x186.png/cc0000/ffffff',
    upvoted_count: 62,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Līkak',
    title: 'sapien in sapien iaculis congue',
  },
  {
    id: 63,
    description:
      'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    reported_count: null,
    user_id: 713658,
    img: 'http://dummyimage.com/208x119.jpg/cc0000/ffffff',
    upvoted_count: 52,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Poconé',
    title: 'platea dictumst maecenas ut',
  },
  {
    id: 64,
    description: 'Aenean sit amet justo.',
    reported_count: 3,
    user_id: 286473,
    img: 'http://dummyimage.com/188x173.jpg/5fa2dd/ffffff',
    upvoted_count: 27,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 2,
    task_owner: 'cgrosvener1r',
    borough: 'Velykyi Bereznyi',
    title: 'in faucibus orci luctus et ultrices posuere',
  },
  {
    id: 65,
    description: 'Nullam molestie nibh in lectus. Pellentesque at nulla.',
    reported_count: 5,
    user_id: 876771,
    img: 'http://dummyimage.com/224x208.png/5fa2dd/ffffff',
    upvoted_count: 32,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 7,
    task_owner: 'rrobathon1s',
    borough: 'Talisay',
    title: 'felis sed lacus morbi sem mauris',
  },
  {
    id: 66,
    description:
      'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    reported_count: 8,
    user_id: 271143,
    img: 'http://dummyimage.com/155x123.bmp/5fa2dd/ffffff',
    upvoted_count: 30,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Oeiras',
    title: 'nibh in hac habitasse platea',
  },
  {
    id: 67,
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    reported_count: 4,
    user_id: 353806,
    img: 'http://dummyimage.com/248x103.jpg/dddddd/000000',
    upvoted_count: 55,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Xin’an',
    title: 'tempus semper est quam pharetra',
  },
  {
    id: 68,
    description:
      'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
    reported_count: 3,
    user_id: 920950,
    img: 'http://dummyimage.com/199x157.png/cc0000/ffffff',
    upvoted_count: 53,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Clearwater',
    title: 'vestibulum ante ipsum primis',
  },
  {
    id: 69,
    description:
      'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    reported_count: null,
    user_id: 972028,
    img: 'http://dummyimage.com/188x107.jpg/dddddd/000000',
    upvoted_count: 71,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Marne-la-Vallée',
    title: 'porta volutpat erat quisque erat',
  },
  {
    id: 70,
    description:
      'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
    reported_count: null,
    user_id: 639406,
    img: 'http://dummyimage.com/200x101.jpg/5fa2dd/ffffff',
    upvoted_count: 58,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'amcgeneay1x',
    borough: 'Al Jamālīyah',
    title: 'erat quisque erat eros viverra eget',
  },
  {
    id: 71,
    description:
      'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    reported_count: null,
    user_id: 522944,
    img: 'http://dummyimage.com/128x250.bmp/cc0000/ffffff',
    upvoted_count: 31,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'lmapp1y',
    borough: 'Saint-Lin-Laurentides',
    title: 'turpis sed ante vivamus tortor duis mattis egestas metus',
  },
  {
    id: 72,
    description: 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.',
    reported_count: 1,
    user_id: 257814,
    img: 'http://dummyimage.com/231x225.bmp/5fa2dd/ffffff',
    upvoted_count: 73,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ccapinetti1z',
    borough: 'Rio Negro',
    title: 'nulla tellus in sagittis dui vel nisl duis ac',
  },
  {
    id: 73,
    description:
      'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    reported_count: 7,
    user_id: 612266,
    img: 'http://dummyimage.com/143x246.jpg/5fa2dd/ffffff',
    upvoted_count: 49,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Mueang Nonthaburi',
    title: 'nulla eget eros elementum',
  },
  {
    id: 74,
    description:
      'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    reported_count: 1,
    user_id: 630000,
    img: 'http://dummyimage.com/137x167.bmp/ff4444/ffffff',
    upvoted_count: 100,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 5,
    task_owner: 'ncastilljo21',
    borough: 'Jinshandian',
    title: 'porttitor lacus at turpis donec posuere metus vitae',
  },
  {
    id: 75,
    description: 'In quis justo.',
    reported_count: 16,
    user_id: 742315,
    img: 'http://dummyimage.com/178x201.png/dddddd/000000',
    upvoted_count: 44,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'abretland22',
    borough: 'Longonjo',
    title: 'nibh in quis justo maecenas',
  },
  {
    id: 76,
    description: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    reported_count: 10,
    user_id: 144332,
    img: 'http://dummyimage.com/133x105.png/5fa2dd/ffffff',
    upvoted_count: 31,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 7,
    task_owner: 'emapledoore23',
    borough: 'Laau',
    title: 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia',
  },
  {
    id: 77,
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    reported_count: null,
    user_id: 329781,
    img: 'http://dummyimage.com/206x134.jpg/ff4444/ffffff',
    upvoted_count: 1,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 7,
    task_owner: 'shemstead24',
    borough: 'Logovskoye',
    title: 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam',
  },
  {
    id: 78,
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
    reported_count: 10,
    user_id: 728171,
    img: 'http://dummyimage.com/208x167.bmp/ff4444/ffffff',
    upvoted_count: 39,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'apaulucci25',
    borough: 'Parizh',
    title: 'aliquet massa id lobortis convallis',
  },
  {
    id: 79,
    description: 'Maecenas pulvinar lobortis est.',
    reported_count: null,
    user_id: 952992,
    img: 'http://dummyimage.com/236x120.bmp/5fa2dd/ffffff',
    upvoted_count: 68,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Kangping',
    title: 'lacinia nisi venenatis tristique',
  },
  {
    id: 80,
    description: 'Proin eu mi. Nulla ac enim.',
    reported_count: 3,
    user_id: 200016,
    img: 'http://dummyimage.com/167x139.jpg/ff4444/ffffff',
    upvoted_count: 24,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Hat Yai',
    title: 'suspendisse ornare consequat lectus in est',
  },
  {
    id: 81,
    description:
      'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    reported_count: null,
    user_id: 393345,
    img: 'http://dummyimage.com/137x155.png/ff4444/ffffff',
    upvoted_count: 45,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Krasnaya Polyana',
    title: 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum',
  },
  {
    id: 82,
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.',
    reported_count: 10,
    user_id: 745250,
    img: 'http://dummyimage.com/125x214.png/cc0000/ffffff',
    upvoted_count: 49,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 1,
    task_owner: 'habbot29',
    borough: 'Fairview',
    title: 'vulputate ut ultrices vel augue vestibulum ante ipsum',
  },
  {
    id: 83,
    description:
      'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    reported_count: null,
    user_id: 977401,
    img: 'http://dummyimage.com/246x222.bmp/cc0000/ffffff',
    upvoted_count: 6,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Jevišovice',
    title: 'non interdum in ante vestibulum',
  },
  {
    id: 84,
    description:
      'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
    reported_count: null,
    user_id: 568566,
    img: 'http://dummyimage.com/199x211.jpg/ff4444/ffffff',
    upvoted_count: 34,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ggleadhall2b',
    borough: 'Campos',
    title: 'adipiscing molestie hendrerit at vulputate vitae nisl',
  },
  {
    id: 85,
    description:
      'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',
    reported_count: 3,
    user_id: 922131,
    img: 'http://dummyimage.com/109x161.bmp/cc0000/ffffff',
    upvoted_count: 68,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Hexiangqiao',
    title: 'et magnis dis parturient montes nascetur ridiculus mus vivamus',
  },
  {
    id: 86,
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    reported_count: 13,
    user_id: 364508,
    img: 'http://dummyimage.com/216x163.bmp/ff4444/ffffff',
    upvoted_count: 54,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'scronshaw2d',
    borough: 'Güiria',
    title: 'lacinia aenean sit amet justo morbi ut odio',
  },
  {
    id: 87,
    description:
      'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
    reported_count: 2,
    user_id: 956801,
    img: 'http://dummyimage.com/135x158.bmp/cc0000/ffffff',
    upvoted_count: 25,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Cieurih Satu',
    title: 'in libero ut massa volutpat convallis',
  },
  {
    id: 88,
    description: 'Etiam faucibus cursus urna.',
    reported_count: 13,
    user_id: 245142,
    img: 'http://dummyimage.com/247x131.jpg/ff4444/ffffff',
    upvoted_count: 35,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 6,
    task_owner: 'rblanshard2f',
    borough: 'Lillehammer',
    title: 'at velit eu est congue',
  },
  {
    id: 89,
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
    reported_count: null,
    user_id: 824903,
    img: 'http://dummyimage.com/167x241.png/5fa2dd/ffffff',
    upvoted_count: 7,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'lnilges2g',
    borough: 'Şurmān',
    title: 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam',
  },
  {
    id: 90,
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    reported_count: null,
    user_id: 476647,
    img: 'http://dummyimage.com/220x107.png/5fa2dd/ffffff',
    upvoted_count: 25,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Molepolole',
    title: 'justo morbi ut odio cras mi pede',
  },
  {
    id: 91,
    description:
      'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
    reported_count: 12,
    user_id: 775496,
    img: 'http://dummyimage.com/245x125.jpg/5fa2dd/ffffff',
    upvoted_count: 53,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'aplevin2i',
    borough: 'Łysomice',
    title: 'orci vehicula condimentum curabitur in libero ut massa volutpat convallis',
  },
  {
    id: 92,
    description:
      'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
    reported_count: null,
    user_id: 853701,
    img: 'http://dummyimage.com/182x239.jpg/dddddd/000000',
    upvoted_count: 10,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 9,
    task_owner: 'abelhomme2j',
    borough: 'Hitoyoshi',
    title: 'aliquet maecenas leo odio condimentum id',
  },
  {
    id: 93,
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    reported_count: 2,
    user_id: 614667,
    img: 'http://dummyimage.com/142x136.png/cc0000/ffffff',
    upvoted_count: 46,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 0,
    task_owner: 'rclaque2k',
    borough: 'Sambirobyong',
    title: 'vel est donec odio justo',
  },
  {
    id: 94,
    description:
      'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
    reported_count: null,
    user_id: 150512,
    img: 'http://dummyimage.com/238x109.jpg/ff4444/ffffff',
    upvoted_count: 25,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
    borough: 'Tagnanan',
    title: 'quam sollicitudin vitae consectetuer eget',
  },
  {
    id: 95,
    description:
      'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
    reported_count: 10,
    user_id: 538174,
    img: 'http://dummyimage.com/226x180.png/5fa2dd/ffffff',
    upvoted_count: 10,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'uhessle2m',
    borough: 'Siukh',
    title: 'sit amet nulla quisque',
  },
  {
    id: 96,
    description: 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    reported_count: null,
    user_id: 867694,
    img: 'http://dummyimage.com/173x224.bmp/dddddd/000000',
    upvoted_count: 74,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 5,
    task_owner: 'atuiller2n',
    borough: 'Jian’ou',
    title: 'justo in blandit ultrices enim',
  },
  {
    id: 97,
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
    reported_count: 6,
    user_id: 879561,
    img: 'http://dummyimage.com/229x114.bmp/cc0000/ffffff',
    upvoted_count: 33,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 2,
    task_owner: 'gseamon2o',
    borough: 'Nanshan',
    title: 'amet lobortis sapien sapien non mi integer ac neque',
  },
  {
    id: 98,
    description:
      'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',
    reported_count: null,
    user_id: 853315,
    img: 'http://dummyimage.com/246x184.png/dddddd/000000',
    upvoted_count: 54,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'kuglow2p',
    borough: 'Yili',
    title: 'maecenas leo odio condimentum id luctus nec molestie',
  },
  {
    id: 99,
    description: 'Duis at velit eu est congue elementum.',
    reported_count: null,
    user_id: 620149,
    img: 'http://dummyimage.com/209x216.jpg/cc0000/ffffff',
    upvoted_count: 44,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 6,
    task_owner: 'jpankhurst2q',
    borough: 'Mertert',
    title: 'pede ullamcorper augue a suscipit nulla elit ac',
  },
  {
    id: 100,
    description:
      'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',
    reported_count: null,
    user_id: 497108,
    img: 'http://dummyimage.com/172x231.png/5fa2dd/ffffff',
    upvoted_count: 12,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 7,
    task_owner: 'njanuszkiewicz2r',
    borough: 'Putrajaya',
    title: 'feugiat et eros vestibulum ac est lacinia',
  },
];

const IssuesPage = (props) => {
  const [sortVal, setSortVal] = useState('id');
  const exampleData = example;
  const [data, setData] = useState(example);
  const [filterVal, setFilterVal] = useState();
  const [borough, setBorough] = useState('all');
  const [sort, setSort] = useState('validations');
  const [order, setOrder] = useState('desc');

  const filterData = (filter) => {
    let arr = [];
    for (var i = 0; i < example.length; i++) {
      let tempArr = Object.values(example[i]);
      let strArr = tempArr.map((val) => String(val));
      if (strArr.includes(filter)) {
        arr.push(example[i]);
      }
    }
    setData(arr);
  };

  const clickHandler = (e) => {
    setFilterVal(e.target.value);
    filterData(e.target.value);
  };
  return (
    <div>
      <label>Borough: </label>
      <select
        onChange={(e) => {
          setBorough(e.target.value);
        }}
      >
        <option value="all"> All </option>
        <option value="manhattan"> Manhattan </option>
        <option value="brooklyn"> Brooklyn </option>
        <option value="bronx"> Bronx </option>
        <option value="queens"> Queens </option>
        <option value="staten"> Staten Island </option>
      </select>
      <label>Sort: </label>
      <select
        onChange={(e) => {
          setSort(e.target.value);
        }}
      >
        <option value="validations"> Validations </option>
        <option value="upvotes"> Upvotes </option>
        <option value="reports"> Reports </option>
      </select>
      <label>Order: </label>
      <select
        onChange={(e) => {
          setOrder(e.target.value);
        }}
      >
        <option value="asc"> Ascending </option>
        <option value="desc"> Descending </option>
      </select>
      <button onClick={(e) => clickHandler(e)}>Submit</button>
      {/* <Statuses /> */}
      <IssuesList
        sortVal={sortVal}
        setSortVal={setSortVal}
        issues={data}
        setData={setData}
        data={data}
      />
    </div>
  );
};

export default IssuesPage;
