import React, { useState } from 'react';
import IssuesList from './IssuesList';
const example = [
  {
    id: 1,
    description:
      'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
    reported_count: 10,
    user_id: 572013,
    img: 'http://dummyimage.com/175x215.bmp/5fa2dd/ffffff',
    upvoted_count: 19,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 0,
    task_owner: 'kdampier0',
  },
  {
    id: 2,
    description: 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
    reported_count: null,
    user_id: 605013,
    img: 'http://dummyimage.com/100x153.jpg/ff4444/ffffff',
    upvoted_count: 7,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 3,
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    reported_count: null,
    user_id: 960850,
    img: 'http://dummyimage.com/207x120.jpg/5fa2dd/ffffff',
    upvoted_count: 19,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 4,
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    reported_count: null,
    user_id: 795506,
    img: 'http://dummyimage.com/240x133.jpg/cc0000/ffffff',
    upvoted_count: 98,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ifynan3',
  },
  {
    id: 5,
    description: 'Etiam vel augue. Vestibulum rutrum rutrum neque.',
    reported_count: null,
    user_id: 715842,
    img: 'http://dummyimage.com/122x117.bmp/ff4444/ffffff',
    upvoted_count: 83,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 6,
    description:
      'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',
    reported_count: 14,
    user_id: 225215,
    img: 'http://dummyimage.com/102x154.png/dddddd/000000',
    upvoted_count: 43,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 7,
    description:
      'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.',
    reported_count: 2,
    user_id: 225556,
    img: 'http://dummyimage.com/117x141.jpg/ff4444/ffffff',
    upvoted_count: 41,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'csheppard6',
  },
  {
    id: 8,
    description:
      'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    reported_count: null,
    user_id: 364240,
    img: 'http://dummyimage.com/153x120.png/dddddd/000000',
    upvoted_count: 24,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 9,
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',
    reported_count: 1,
    user_id: 291546,
    img: 'http://dummyimage.com/157x185.png/5fa2dd/ffffff',
    upvoted_count: 20,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 10,
    description:
      'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    reported_count: null,
    user_id: 881382,
    img: 'http://dummyimage.com/119x218.jpg/cc0000/ffffff',
    upvoted_count: 57,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 11,
    description:
      'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    reported_count: null,
    user_id: 340148,
    img: 'http://dummyimage.com/213x130.jpg/dddddd/000000',
    upvoted_count: 71,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 12,
    description:
      'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
    reported_count: null,
    user_id: 364735,
    img: 'http://dummyimage.com/144x116.jpg/dddddd/000000',
    upvoted_count: 19,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 13,
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    reported_count: null,
    user_id: 290571,
    img: 'http://dummyimage.com/116x149.jpg/dddddd/000000',
    upvoted_count: 39,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 9,
    task_owner: 'jsandellsc',
  },
  {
    id: 14,
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
    reported_count: 7,
    user_id: 943880,
    img: 'http://dummyimage.com/203x144.png/ff4444/ffffff',
    upvoted_count: 8,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 15,
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    reported_count: null,
    user_id: 274040,
    img: 'http://dummyimage.com/164x215.png/ff4444/ffffff',
    upvoted_count: 27,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 16,
    description:
      'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    reported_count: null,
    user_id: 360281,
    img: 'http://dummyimage.com/189x235.png/dddddd/000000',
    upvoted_count: 53,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 8,
    task_owner: 'shenfref',
  },
  {
    id: 17,
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',
    reported_count: 19,
    user_id: 139321,
    img: 'http://dummyimage.com/214x154.png/dddddd/000000',
    upvoted_count: 84,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'fadanezg',
  },
  {
    id: 18,
    description: 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
    reported_count: 11,
    user_id: 199602,
    img: 'http://dummyimage.com/112x169.bmp/dddddd/000000',
    upvoted_count: 42,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 19,
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    reported_count: 6,
    user_id: 306914,
    img: 'http://dummyimage.com/161x151.png/ff4444/ffffff',
    upvoted_count: 7,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 20,
    description:
      'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    reported_count: null,
    user_id: 745337,
    img: 'http://dummyimage.com/225x131.png/ff4444/ffffff',
    upvoted_count: 64,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 7,
    task_owner: 'rchidlerj',
  },
  {
    id: 21,
    description:
      'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',
    reported_count: 6,
    user_id: 622541,
    img: 'http://dummyimage.com/173x195.png/cc0000/ffffff',
    upvoted_count: 57,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ldilworthk',
  },
  {
    id: 22,
    description: 'Nulla justo.',
    reported_count: null,
    user_id: 464223,
    img: 'http://dummyimage.com/128x131.jpg/dddddd/000000',
    upvoted_count: 1,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'adergesl',
  },
  {
    id: 23,
    description:
      'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
    reported_count: 4,
    user_id: 190565,
    img: 'http://dummyimage.com/151x182.jpg/5fa2dd/ffffff',
    upvoted_count: 100,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 24,
    description:
      'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',
    reported_count: 4,
    user_id: 256305,
    img: 'http://dummyimage.com/115x220.jpg/ff4444/ffffff',
    upvoted_count: 37,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 25,
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    reported_count: 10,
    user_id: 876119,
    img: 'http://dummyimage.com/202x114.png/ff4444/ffffff',
    upvoted_count: 85,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 26,
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
    reported_count: null,
    user_id: 561865,
    img: 'http://dummyimage.com/163x212.png/ff4444/ffffff',
    upvoted_count: 9,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 0,
    task_owner: 'mmcilwainp',
  },
  {
    id: 27,
    description: 'In hac habitasse platea dictumst.',
    reported_count: null,
    user_id: 291400,
    img: 'http://dummyimage.com/196x156.jpg/cc0000/ffffff',
    upvoted_count: 87,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'lslanyq',
  },
  {
    id: 28,
    description:
      'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
    reported_count: 9,
    user_id: 553166,
    img: 'http://dummyimage.com/190x171.png/ff4444/ffffff',
    upvoted_count: 46,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 1,
    task_owner: 'ngurnellr',
  },
  {
    id: 29,
    description:
      'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.',
    reported_count: 17,
    user_id: 695796,
    img: 'http://dummyimage.com/197x132.png/ff4444/ffffff',
    upvoted_count: 55,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 30,
    description:
      'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
    reported_count: null,
    user_id: 650255,
    img: 'http://dummyimage.com/229x180.png/ff4444/ffffff',
    upvoted_count: 23,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 31,
    description:
      'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
    reported_count: 13,
    user_id: 547757,
    img: 'http://dummyimage.com/120x151.jpg/5fa2dd/ffffff',
    upvoted_count: 61,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'cdugmoreu',
  },
  {
    id: 32,
    description:
      'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    reported_count: 19,
    user_id: 786961,
    img: 'http://dummyimage.com/230x191.jpg/cc0000/ffffff',
    upvoted_count: 28,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 33,
    description:
      'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.',
    reported_count: null,
    user_id: 178167,
    img: 'http://dummyimage.com/174x202.png/5fa2dd/ffffff',
    upvoted_count: 57,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 34,
    description:
      'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    reported_count: 19,
    user_id: 244867,
    img: 'http://dummyimage.com/102x241.png/dddddd/000000',
    upvoted_count: 28,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 0,
    task_owner: 'ddevenniex',
  },
  {
    id: 35,
    description: 'Maecenas rhoncus aliquam lacus.',
    reported_count: null,
    user_id: 539486,
    img: 'http://dummyimage.com/207x207.jpg/dddddd/000000',
    upvoted_count: 32,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 36,
    description:
      'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',
    reported_count: 7,
    user_id: 164768,
    img: 'http://dummyimage.com/223x125.bmp/5fa2dd/ffffff',
    upvoted_count: 70,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 3,
    task_owner: 'ssignorelliz',
  },
  {
    id: 37,
    description: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
    reported_count: null,
    user_id: 813743,
    img: 'http://dummyimage.com/156x155.bmp/dddddd/000000',
    upvoted_count: 48,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 9,
    task_owner: 'wantonomolii10',
  },
  {
    id: 38,
    description:
      'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    reported_count: 5,
    user_id: 361063,
    img: 'http://dummyimage.com/217x185.png/dddddd/000000',
    upvoted_count: 21,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 5,
    task_owner: 'jguiducci11',
  },
  {
    id: 39,
    description:
      'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
    reported_count: null,
    user_id: 865547,
    img: 'http://dummyimage.com/184x124.jpg/5fa2dd/ffffff',
    upvoted_count: 46,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 40,
    description: 'Donec posuere metus vitae ipsum.',
    reported_count: null,
    user_id: 678161,
    img: 'http://dummyimage.com/165x235.jpg/ff4444/ffffff',
    upvoted_count: 18,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 1,
    task_owner: 'vglenwright13',
  },
  {
    id: 41,
    description:
      'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',
    reported_count: null,
    user_id: 919047,
    img: 'http://dummyimage.com/213x193.png/cc0000/ffffff',
    upvoted_count: 71,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 5,
    task_owner: 'pgergher14',
  },
  {
    id: 42,
    description:
      'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    reported_count: null,
    user_id: 686518,
    img: 'http://dummyimage.com/111x161.jpg/ff4444/ffffff',
    upvoted_count: 22,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'lkegg15',
  },
  {
    id: 43,
    description:
      'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
    reported_count: null,
    user_id: 479720,
    img: 'http://dummyimage.com/119x153.jpg/ff4444/ffffff',
    upvoted_count: 54,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'rmelmoth16',
  },
  {
    id: 44,
    description:
      'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
    reported_count: 12,
    user_id: 816023,
    img: 'http://dummyimage.com/179x238.jpg/ff4444/ffffff',
    upvoted_count: 16,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 5,
    task_owner: 'ggierek17',
  },
  {
    id: 45,
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    reported_count: null,
    user_id: 458503,
    img: 'http://dummyimage.com/183x206.png/ff4444/ffffff',
    upvoted_count: 52,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 3,
    task_owner: 'ecleugher18',
  },
  {
    id: 46,
    description:
      'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
    reported_count: null,
    user_id: 661566,
    img: 'http://dummyimage.com/198x189.jpg/cc0000/ffffff',
    upvoted_count: 18,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'smandel19',
  },
  {
    id: 47,
    description:
      'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',
    reported_count: null,
    user_id: 637612,
    img: 'http://dummyimage.com/245x105.png/cc0000/ffffff',
    upvoted_count: 39,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 48,
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.',
    reported_count: null,
    user_id: 150618,
    img: 'http://dummyimage.com/210x161.png/dddddd/000000',
    upvoted_count: 79,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'kpeller1b',
  },
  {
    id: 49,
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    reported_count: null,
    user_id: 582260,
    img: 'http://dummyimage.com/156x239.png/ff4444/ffffff',
    upvoted_count: 88,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'cbaylay1c',
  },
  {
    id: 50,
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    reported_count: null,
    user_id: 365292,
    img: 'http://dummyimage.com/170x215.jpg/5fa2dd/ffffff',
    upvoted_count: 56,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 51,
    description: 'Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    reported_count: 6,
    user_id: 390622,
    img: 'http://dummyimage.com/230x133.png/ff4444/ffffff',
    upvoted_count: 43,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'tdyke1e',
  },
  {
    id: 52,
    description:
      'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    reported_count: 6,
    user_id: 651422,
    img: 'http://dummyimage.com/183x182.png/ff4444/ffffff',
    upvoted_count: 22,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 8,
    task_owner: 'skirtlan1f',
  },
  {
    id: 53,
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    reported_count: 16,
    user_id: 756737,
    img: 'http://dummyimage.com/160x217.png/cc0000/ffffff',
    upvoted_count: 23,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'mlinstead1g',
  },
  {
    id: 54,
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    reported_count: 7,
    user_id: 990052,
    img: 'http://dummyimage.com/224x107.png/5fa2dd/ffffff',
    upvoted_count: 51,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'tsammons1h',
  },
  {
    id: 55,
    description:
      'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    reported_count: 5,
    user_id: 831266,
    img: 'http://dummyimage.com/246x248.jpg/dddddd/000000',
    upvoted_count: 7,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'cmccaughey1i',
  },
  {
    id: 56,
    description:
      'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',
    reported_count: null,
    user_id: 579467,
    img: 'http://dummyimage.com/186x178.jpg/dddddd/000000',
    upvoted_count: 35,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'atointon1j',
  },
  {
    id: 57,
    description:
      'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    reported_count: 2,
    user_id: 871316,
    img: 'http://dummyimage.com/129x194.bmp/ff4444/ffffff',
    upvoted_count: 48,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 5,
    task_owner: 'disaaksohn1k',
  },
  {
    id: 58,
    description:
      'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    reported_count: null,
    user_id: 251767,
    img: 'http://dummyimage.com/135x107.png/dddddd/000000',
    upvoted_count: 59,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'dbrake1l',
  },
  {
    id: 59,
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
    reported_count: 8,
    user_id: 585464,
    img: 'http://dummyimage.com/175x207.bmp/dddddd/000000',
    upvoted_count: 66,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 60,
    description:
      'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
    reported_count: null,
    user_id: 925628,
    img: 'http://dummyimage.com/185x203.png/5fa2dd/ffffff',
    upvoted_count: 37,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 61,
    description: 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',
    reported_count: 15,
    user_id: 709947,
    img: 'http://dummyimage.com/190x181.png/dddddd/000000',
    upvoted_count: 67,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'vtombs1o',
  },
  {
    id: 62,
    description: 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    reported_count: 15,
    user_id: 692940,
    img: 'http://dummyimage.com/131x236.bmp/ff4444/ffffff',
    upvoted_count: 65,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 63,
    description:
      'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.',
    reported_count: 1,
    user_id: 445486,
    img: 'http://dummyimage.com/218x223.png/5fa2dd/ffffff',
    upvoted_count: 16,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 64,
    description: 'In hac habitasse platea dictumst.',
    reported_count: 18,
    user_id: 758669,
    img: 'http://dummyimage.com/200x213.bmp/ff4444/ffffff',
    upvoted_count: 26,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 65,
    description:
      'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    reported_count: 8,
    user_id: 285347,
    img: 'http://dummyimage.com/138x124.bmp/5fa2dd/ffffff',
    upvoted_count: 64,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 66,
    description:
      'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
    reported_count: null,
    user_id: 234189,
    img: 'http://dummyimage.com/185x151.png/cc0000/ffffff',
    upvoted_count: 29,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 1,
    task_owner: 'mstoker1t',
  },
  {
    id: 67,
    description:
      'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.',
    reported_count: null,
    user_id: 728826,
    img: 'http://dummyimage.com/191x181.png/dddddd/000000',
    upvoted_count: 69,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'jferrer1u',
  },
  {
    id: 68,
    description:
      'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.',
    reported_count: 18,
    user_id: 847225,
    img: 'http://dummyimage.com/119x127.png/5fa2dd/ffffff',
    upvoted_count: 98,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 8,
    task_owner: 'rcerman1v',
  },
  {
    id: 69,
    description: 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',
    reported_count: null,
    user_id: 971220,
    img: 'http://dummyimage.com/161x123.png/cc0000/ffffff',
    upvoted_count: 37,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'sbutfield1w',
  },
  {
    id: 70,
    description:
      'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',
    reported_count: null,
    user_id: 184430,
    img: 'http://dummyimage.com/202x114.jpg/5fa2dd/ffffff',
    upvoted_count: 29,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'dmabley1x',
  },
  {
    id: 71,
    description: 'Vestibulum sed magna at nunc commodo placerat.',
    reported_count: 4,
    user_id: 133723,
    img: 'http://dummyimage.com/204x227.bmp/dddddd/000000',
    upvoted_count: 17,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'pfeaks1y',
  },
  {
    id: 72,
    description:
      'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    reported_count: 19,
    user_id: 265292,
    img: 'http://dummyimage.com/120x211.bmp/cc0000/ffffff',
    upvoted_count: 24,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'hassad1z',
  },
  {
    id: 73,
    description: 'Maecenas rhoncus aliquam lacus.',
    reported_count: null,
    user_id: 458862,
    img: 'http://dummyimage.com/151x101.bmp/dddddd/000000',
    upvoted_count: 48,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 1,
    task_owner: 'hguy20',
  },
  {
    id: 74,
    description:
      'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
    reported_count: null,
    user_id: 186784,
    img: 'http://dummyimage.com/234x223.bmp/cc0000/ffffff',
    upvoted_count: 41,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'smillthorpe21',
  },
  {
    id: 75,
    description: 'Donec ut dolor.',
    reported_count: null,
    user_id: 776042,
    img: 'http://dummyimage.com/219x203.bmp/cc0000/ffffff',
    upvoted_count: 4,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 0,
    task_owner: 'fwimbridge22',
  },
  {
    id: 76,
    description:
      'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    reported_count: null,
    user_id: 118994,
    img: 'http://dummyimage.com/225x112.jpg/dddddd/000000',
    upvoted_count: 57,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 3,
    task_owner: 'splewright23',
  },
  {
    id: 77,
    description:
      'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
    reported_count: 17,
    user_id: 571740,
    img: 'http://dummyimage.com/240x121.bmp/dddddd/000000',
    upvoted_count: 71,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 78,
    description:
      'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    reported_count: null,
    user_id: 285419,
    img: 'http://dummyimage.com/122x117.bmp/5fa2dd/ffffff',
    upvoted_count: 53,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 0,
    task_owner: 'larminger25',
  },
  {
    id: 79,
    description:
      'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
    reported_count: 16,
    user_id: 549236,
    img: 'http://dummyimage.com/150x233.bmp/5fa2dd/ffffff',
    upvoted_count: 71,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'ecornew26',
  },
  {
    id: 80,
    description:
      'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',
    reported_count: null,
    user_id: 921296,
    img: 'http://dummyimage.com/133x170.jpg/dddddd/000000',
    upvoted_count: 3,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'bagnew27',
  },
  {
    id: 81,
    description: 'Nulla mollis molestie lorem. Quisque ut erat.',
    reported_count: 14,
    user_id: 679226,
    img: 'http://dummyimage.com/176x115.bmp/5fa2dd/ffffff',
    upvoted_count: 79,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 82,
    description:
      'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',
    reported_count: null,
    user_id: 240790,
    img: 'http://dummyimage.com/213x152.bmp/dddddd/000000',
    upvoted_count: 35,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 83,
    description:
      'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',
    reported_count: null,
    user_id: 219013,
    img: 'http://dummyimage.com/101x198.png/ff4444/ffffff',
    upvoted_count: 25,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'pgieraths2a',
  },
  {
    id: 84,
    description:
      'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    reported_count: 3,
    user_id: 126102,
    img: 'http://dummyimage.com/110x185.jpg/cc0000/ffffff',
    upvoted_count: 1,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 85,
    description:
      'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',
    reported_count: null,
    user_id: 488768,
    img: 'http://dummyimage.com/220x108.bmp/dddddd/000000',
    upvoted_count: 13,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'misaksen2c',
  },
  {
    id: 86,
    description: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    reported_count: 7,
    user_id: 795712,
    img: 'http://dummyimage.com/227x114.png/dddddd/000000',
    upvoted_count: 84,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 87,
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    reported_count: null,
    user_id: 377787,
    img: 'http://dummyimage.com/173x142.png/cc0000/ffffff',
    upvoted_count: 52,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'rsuch2e',
  },
  {
    id: 88,
    description:
      'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    reported_count: 12,
    user_id: 620194,
    img: 'http://dummyimage.com/155x184.png/cc0000/ffffff',
    upvoted_count: 10,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 89,
    description: 'Nam nulla.',
    reported_count: null,
    user_id: 888712,
    img: 'http://dummyimage.com/229x126.jpg/ff4444/ffffff',
    upvoted_count: 43,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 2,
    task_owner: 'fkunc2g',
  },
  {
    id: 90,
    description:
      'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    reported_count: 15,
    user_id: 656217,
    img: 'http://dummyimage.com/105x247.png/5fa2dd/ffffff',
    upvoted_count: 14,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'hpawlett2h',
  },
  {
    id: 91,
    description:
      'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    reported_count: null,
    user_id: 646288,
    img: 'http://dummyimage.com/122x155.jpg/ff4444/ffffff',
    upvoted_count: 88,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'emcmakin2i',
  },
  {
    id: 92,
    description:
      'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    reported_count: 11,
    user_id: 689028,
    img: 'http://dummyimage.com/155x173.jpg/ff4444/ffffff',
    upvoted_count: 76,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 93,
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    reported_count: 9,
    user_id: 365663,
    img: 'http://dummyimage.com/222x217.jpg/ff4444/ffffff',
    upvoted_count: 9,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/3/2020',
    confirm_resolved_count: 7,
    task_owner: 'rstorek2k',
  },
  {
    id: 94,
    description:
      'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.',
    reported_count: null,
    user_id: 995365,
    img: 'http://dummyimage.com/197x100.png/5fa2dd/ffffff',
    upvoted_count: 1,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'fsporner2l',
  },
  {
    id: 95,
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    reported_count: null,
    user_id: 920312,
    img: 'http://dummyimage.com/133x247.bmp/ff4444/ffffff',
    upvoted_count: 57,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 8,
    task_owner: 'tdurbann2m',
  },
  {
    id: 96,
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    reported_count: null,
    user_id: 437675,
    img: 'http://dummyimage.com/100x125.jpg/cc0000/ffffff',
    upvoted_count: 56,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 1,
    task_owner: 'bcowcha2n',
  },
  {
    id: 97,
    description: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
    reported_count: 4,
    user_id: 610462,
    img: 'http://dummyimage.com/230x121.bmp/cc0000/ffffff',
    upvoted_count: 70,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
  {
    id: 98,
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    reported_count: 8,
    user_id: 954754,
    img: 'http://dummyimage.com/180x220.jpg/cc0000/ffffff',
    upvoted_count: 13,
    resolution_status: 3,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: '11/2/2020',
    confirm_resolved_count: 4,
    task_owner: 'kslayton2p',
  },
  {
    id: 99,
    description:
      'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.',
    reported_count: null,
    user_id: 491257,
    img: 'http://dummyimage.com/212x165.bmp/cc0000/ffffff',
    upvoted_count: 94,
    resolution_status: 2,
    date_issued: '10/30/2020',
    date_marked_in_progress: '11/1/2020',
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: 'kwestoff2q',
  },
  {
    id: 100,
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',
    reported_count: 19,
    user_id: 105808,
    img: 'http://dummyimage.com/214x222.jpg/ff4444/ffffff',
    upvoted_count: 82,
    resolution_status: 1,
    date_issued: '10/30/2020',
    date_marked_in_progress: null,
    date_marked_resolved: null,
    confirm_resolved_count: null,
    task_owner: null,
  },
];
const IssuesPage = (props) => (
  <div>
    {/* <Statuses /> */}
    <IssuesList issues={example} />
  </div>
);

export default IssuesPage;
